# Generated by Django 3.1.7 on 2021-03-25 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('DOB', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('position', models.BigIntegerField(blank=True, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.BigIntegerField(blank=True, null=True)),
                ('children', models.BigIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_image', models.BigIntegerField(blank=True, null=True)),
                ('video', models.BigIntegerField(blank=True, null=True)),
                ('certificates', models.BigIntegerField(blank=True, null=True)),
                ('id_proofs', models.BigIntegerField(blank=True, null=True)),
                ('last_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opportunties', models.CharField(blank=True, max_length=255, null=True)),
                ('full_time', models.IntegerField(blank=True, null=True)),
                ('publish', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('relocate_location', models.TextField(blank=True, null=True)),
                ('primary_subject', models.BigIntegerField(blank=True, null=True)),
                ('standards_taught', models.TextField(blank=True, null=True)),
                ('secondary_subject', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('ctet', models.IntegerField(blank=True, null=True)),
                ('ctet_paper', models.CharField(blank=True, max_length=255, null=True)),
                ('net', models.IntegerField(blank=True, null=True)),
                ('professional_training', models.IntegerField(blank=True, null=True)),
                ('examiner', models.IntegerField(blank=True, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('training_days', models.IntegerField(blank=True, null=True)),
                ('monthly_passed', models.CharField(blank=True, max_length=255, null=True)),
                ('year_passed', models.CharField(blank=True, max_length=255, null=True)),
                ('school_board', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_year', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('completed_step', models.IntegerField(blank=True, null=True)),
                ('completed_status', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_teacherprofiles_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_teacherprofiles_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_teacherprofiles_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
